{
  "openapi": "3.0.0",
  "info": {
    "title": "Coffee_Bloom  Node + MySQL API",
    "description": "Coffee Bloom API Documentation",
    "version": "1.0.0"
  },
  "paths": {
    "/auth/signup": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "User Signup",
        "description": "Create a new user account",
        "responses": {
          "201": {
            "description": "User registered successfully",
            "content": {
              "application/json": {
                "example": {
                  "rescode": 1,
                  "message": "User registered",
                  "data": {
                    "id": 1,
                    "name": "Name",
                    "email": "test@gmail.com",
                    "address": "Address",
                    "token": "jwt-token"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          }
        },
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name",
                  "email",
                  "password",
                  "confirm_password",
                  "address"
                ],
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Ali Khan"
                  },
                  "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@test.com"
                  },
                  "password": {
                    "type": "string",
                    "format": "password",
                    "example": "123456"
                  },
                  "confirm_password": {
                    "type": "string",
                    "format": "password",
                    "example": "123456"
                  },
                  "address": {
                    "type": "string",
                    "example": "Lahore"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "User Login",
        "description": "Login with email and password",
        "responses": {
          "200": {
            "description": "Login successful",
            "content": {
              "application/json": {
                "example": {
                  "rescode": 1,
                  "message": "Login successful",
                  "data": {
                    "accessToken": "token",
                    "refreshToken": "token"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email",
                  "password"
                ],
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@test.com"
                  },
                  "password": {
                    "type": "string",
                    "format": "password",
                    "example": "123456"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/refresh": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "New Access Token",
        "description": "Generate new access token by refresh token",
        "responses": {
          "200": {
            "description": "Generate new access token",
            "content": {
              "application/json": {
                "example": {
                  "rescode": 1,
                  "message": "Access token generated successfully",
                  "data": {
                    "accessToken": "token"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "refresh_token": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/profile/{id}": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Get sigle user",
        "description": "Fetch single user",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User fetched successfully",
            "content": {
              "application/json": {
                "example": {
                  "rescode": 1,
                  "message": "Users fetched successfully",
                  "data": [
                    {
                      "user_id": 1,
                      "name": "Name1",
                      "email": "test@example.com",
                      "address": "Your Address"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/users/": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Get all users",
        "description": "Fetch list of all active users",
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Users fetched successfully",
            "content": {
              "application/json": {
                "example": {
                  "rescode": 1,
                  "message": "Users fetched successfully",
                  "data": [
                    {
                      "user_id": 1,
                      "name": "Name1",
                      "email": "test@example.com",
                      "address": "Your Address"
                    },
                    {
                      "user_id": 2,
                      "name": "Name2",
                      "email": "test@example.com",
                      "address": "Your Address"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/users/{id}": {
      "put": {
        "tags": [
          "users"
        ],
        "summary": "Get sigle user",
        "description": "Fetch single user",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "required": [
                  "name",
                  "email",
                  "password",
                  "confirm_password",
                  "address"
                ],
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Ali Khan"
                  },
                  "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@test.com"
                  },
                  "password": {
                    "type": "string",
                    "format": "password",
                    "example": "123456"
                  },
                  "address": {
                    "type": "string",
                    "example": "Lahore"
                  },
                  "image": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "BearerAuth": []
    }
  ]
}